from typing import Any, Sequence, TypeVar

from numpy import _ArrayLike, ndarray, AxesType, complexfloating

_S = TypeVar('_S')

def fft(a: _ArrayLike[Any], n: int = None, axis: int = -1, norm: str = None,
        ) -> ndarray[complexfloating]: ...
def ifft(a: _ArrayLike[Any], n: int = None, axis: int = -1, norm: str = None,
        ) -> ndarray[complexfloating]: ...
def fft2(a: _ArrayLike[Any], s: Sequence[int] = None, axes: Sequence[int] = None,
         norm: str = None) -> ndarray[complexfloating]: ...
def ifft2(a: _ArrayLike[Any], s: Sequence[int] = None, axes: Sequence[int] = None,
         norm: str = None) -> ndarray[complexfloating]: ...
def fftn(a: _ArrayLike[Any], s: Sequence[int] = None, axes: Sequence[int] = None,
         norm: str = None) -> ndarray[complexfloating]: ...
def ifftn(a: _ArrayLike[Any], s: Sequence[int] = None, axes: Sequence[int] = None,
         norm: str = None) -> ndarray[complexfloating]: ...
def fftshift(x: _ArrayLike[_S], axes: AxesType = None) -> ndarray[_S]: ...
def ifftshift(x: _ArrayLike[_S], axes: AxesType = None) -> ndarray[_S]: ...
