from numpy import ndarray, DtypeType, ShapeType, _ArrayLike, floating

from typing import overload

def rand(*args: int) -> ndarray[float]: ...
def ranf(*args: int) -> ndarray[float]: ...
def random(size: ShapeType=None) -> float: ...
def randint(low: int, high: int = None, size: ShapeType = None, dtype: DtypeType = int
            ) -> ndarray[int]: ...
def normal(loc: _ArrayLike[float], scale: _ArrayLike[float],
           size: ShapeType = None) -> ndarray[float]: ...
